{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "4146b225-b2af-4a3f-9867-42c44f1c0a08",
   "metadata": {},
   "source": [
    "Q1. What is an Exception in python? Write the difference between Exceptions and Syntax errors."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "420022cb-8954-4e68-b04d-80a42536b4c7",
   "metadata": {},
   "source": [
    "Syntax errors are mistakes in the source code, such as spelling and punctuation errors, incorrect labels, and so on, which \n",
    "\n",
    "cause an error message to be generated by the compiler. Whereas, Even if a statement or expression is syntactically correct, \n",
    "\n",
    "it may cause an error when an attempt is made to execute it.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "fcfdd1fb-2454-439f-897d-c88364975dfc",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (305637400.py, line 2)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  Cell \u001b[0;32mIn[2], line 2\u001b[0;36m\u001b[0m\n\u001b[0;31m    if True print('This is valid syntax')\u001b[0m\n\u001b[0m            ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "#for example\n",
    "#This is syntax error\n",
    "if True print('This is valid syntax')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "95d29398-315d-4d65-89f6-0872c054e485",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m#This is exception\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m a \u001b[38;5;241m=\u001b[39m \u001b[38;5;241;43m1\u001b[39;49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[38;5;241;43m0\u001b[39;49m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;28mprint\u001b[39m(a)\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "#This is exception\n",
    "#Here the syntax is fine, but when we execute it gives error, which is known as exception.\n",
    "a = 1/0\n",
    "print(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e1b0d1fe-5de6-45b4-bdad-45dbbae865dd",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "60a30ff4-122c-4a3d-8e8d-abe37e82b2b3",
   "metadata": {},
   "source": [
    "Q2. What happens when an exception is not handled? Explain with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "63d8078a-2dce-4e1c-9e01-4fcf15cd65e7",
   "metadata": {},
   "source": [
    "When an exception occurred, if you don't handle it, the program terminates abruptly and the code past the line that caused \n",
    "\n",
    "the exception will not get executed."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "c5c50f27-89ee-47ec-b4ed-48d36d677cc7",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "can only concatenate str (not \"int\") to str",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m#for example\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m a \u001b[38;5;241m=\u001b[39m \u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m2\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m2\u001b[39;49m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[1;32m      4\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mThe statement is executed\u001b[39m\u001b[38;5;124m'\u001b[39m)\n",
      "\u001b[0;31mTypeError\u001b[0m: can only concatenate str (not \"int\") to str"
     ]
    }
   ],
   "source": [
    "#for example\n",
    "a = '2' + 2\n",
    "if True:\n",
    "    print('The statement is executed')\n",
    "    \n",
    "'''Here the exception is not handle therefore the program terminated \n",
    "before implementation of if statement '''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c3c76f7a-a7ee-4707-8a92-5d7229d2d1fa",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "70eed764-1bb9-4140-8203-63f55cc2b562",
   "metadata": {},
   "source": [
    "Q3. Which Python statements are used to catch and handle exceptions? Explain with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "04df9087-4c6a-45f0-8c61-c65f3d6920ab",
   "metadata": {},
   "source": [
    "The try and except block in Python is used to catch and handle exceptions. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "3b979279-24de-4cb0-afbf-6813e8bd8948",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Cannot divide int with str.\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    a = 5 \n",
    "    b = '0'\n",
    "    print(a/b)\n",
    "except:\n",
    "    print('Cannot divide int with str.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ebd57fb5-ec34-41ee-bb4f-ddb72de4d8da",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "14821cc1-450b-4d63-84d8-83f3bba3d08c",
   "metadata": {},
   "source": [
    "Q4. Explain with an example:\n",
    "\n",
    "    a. try and else\n",
    "    \n",
    "    b. finally\n",
    "    \n",
    "    c. raise"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "28d8e221-06fd-4208-b90e-b80e24c2d42e",
   "metadata": {},
   "outputs": [],
   "source": [
    "#try and else\n",
    "# else keyword in a try - except block to define what to do if no errors were raised\n",
    "def number(x):\n",
    "    try:\n",
    "        if x > 1000:\n",
    "            raise ValueError(x)\n",
    "    except ValueError:\n",
    "        print(x, \"is out of allowed range. Please enter number below 1000\")\n",
    "    else:\n",
    "        print(x, \"is within the allowed range\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "5c875ff6-7220-4417-a08e-175829693665",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "100 is within the allowed range\n"
     ]
    }
   ],
   "source": [
    "number(100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "0aaa441a-2f8c-4bb1-8503-06e8a0a4a3b1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "10000 is out of allowed range. Please enter number below 1000\n"
     ]
    }
   ],
   "source": [
    "number(10000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d6dbfbbc-cc16-446f-8670-ca23db8f7ecf",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "0a2cf369-1d0b-4a3e-b7b6-ec1ded9c7906",
   "metadata": {},
   "outputs": [],
   "source": [
    "#finally\n",
    "#The finally block will always be executed, no matter if the try block raises an error or not.\n",
    "def divide(x, y):\n",
    "        try:\n",
    "            result = x / y\n",
    "        except ZeroDivisionError:\n",
    "            print(\"Error: Division by zero doesn't make any sense!\")\n",
    "        else:\n",
    "            print(\"result is\", result)\n",
    "        finally:\n",
    "            print(\"The task is completed\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "ae962eea-81e3-4be2-a287-90158d8e0bb5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "result is 2.0\n",
      "The task is completed\n"
     ]
    }
   ],
   "source": [
    "divide(2,1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "d9251689-d21f-44b5-b192-ac6ebcde58ab",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Division by zero doesn't make any sense!\n",
      "The task is completed\n"
     ]
    }
   ],
   "source": [
    "divide(10,0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ab447832-662e-4202-b84c-428135a18f71",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "8b5cd25e-5de0-4dfa-987e-d6f28f633cf0",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "Only integers are allowed. Please re-assign value.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[23], line 5\u001b[0m\n\u001b[1;32m      2\u001b[0m x \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mData Science\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mtype\u001b[39m(x) \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m----> 5\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mOnly integers are allowed. Please re-assign value.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mTypeError\u001b[0m: Only integers are allowed. Please re-assign value."
     ]
    }
   ],
   "source": [
    "#The raise keyword is used to raise an exception.\n",
    "x = \"Data Science\"\n",
    "\n",
    "if not type(x) is int:\n",
    "    raise TypeError(\"Only integers are allowed. Please re-assign value.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "39121bf5-2a1a-4e8b-8174-e475f6fe6091",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "fd109173-9f85-4c33-a946-ae97d8ea61be",
   "metadata": {},
   "source": [
    "Q5. What are Custom Exceptions in python? Why do we need Custom Exceptions? Explain with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "674046a5-8427-4e64-826c-bce5aec0fb92",
   "metadata": {},
   "source": [
    "Custom exception are user-defined for a particular purpose. They may not be built in errors, but they are useful when we are working on specific data. Also, custom exceptions provide you the flexibility to add attributes and methods that are not part of built-in exceptions."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "8551cded-e7fb-45fd-a89c-6fccac86f4d8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      " -50\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-50\n"
     ]
    }
   ],
   "source": [
    "#Example\n",
    "try:\n",
    "    age = int(input())\n",
    "except:\n",
    "    print(\"Invalid Age\")\n",
    "else:\n",
    "    print(age) #the age is printed irrespective of value. Because there is no error. Therfore, we need custom exception"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3e6d7394-ed9a-408e-8391-ef8fc8528267",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "a09f5ae5-2567-426e-849b-724ff07972e6",
   "metadata": {},
   "source": [
    "Q6. Create a custom exception class. Use this class to handle an exception."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "eab2b9f1-2217-46bc-a25d-dd643ea4897e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      " -5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Value should be greater than Zero and less than 6\n"
     ]
    }
   ],
   "source": [
    "class InputError(Exception):\n",
    "     pass\n",
    "try:\n",
    "    x = int(input())\n",
    "    m =0\n",
    "    if x < 0:\n",
    "        raise InputError\n",
    "    for i in range(1,x+1):\n",
    "        m+=1\n",
    "        for j in range (1,i+1):\n",
    "            print(m, end = \" \")\n",
    "        print(\"\")\n",
    "except InputError:\n",
    "    print('Value should be greater than Zero and less than 6')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "640722d5-ff40-4577-98a7-60d95d8da931",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      " 6\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1 \n",
      "2 2 \n",
      "3 3 3 \n",
      "4 4 4 4 \n",
      "5 5 5 5 5 \n",
      "6 6 6 6 6 6 \n"
     ]
    }
   ],
   "source": [
    "class InputError(Exception):\n",
    "     pass\n",
    "try:\n",
    "    x = int(input())\n",
    "    m =0\n",
    "    if x < 0:\n",
    "        raise InputError\n",
    "    for i in range(1,x+1):\n",
    "        m+=1\n",
    "        for j in range (1,i+1):\n",
    "            print(m, end = \" \")\n",
    "        print(\"\")\n",
    "except InputError:\n",
    "    print('Value should be greater than Zero and less than 6')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f50f5d02-5a0c-46ad-bd79-04997cab8f96",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
